FROM node:22-slim AS base
WORKDIR /opt/app

FROM base AS deps
COPY package*.json ./
RUN npm install podverse-helpers@alpha --save \
    && npm install sharp \
    && npm clean-install

FROM deps AS builder
COPY . .
COPY ./env/alpha.env ./.env.production
RUN npm run build

FROM node:22-slim AS runner
WORKDIR /opt/app
ENV NODE_ENV=production
COPY --from=builder /opt/app/.env.production ./.env.production
COPY --from=builder /opt/app/.next/standalone ./
COPY --from=builder /opt/app/.next/static ./.next/static
COPY --from=builder /opt/app/public ./public
EXPOSE 3000
CMD ["node", "server.js"]