export const core = {
  About: `About`,
  anonymous: `anonymous`,
  Cancel: `Cancel`,
  Clips: `Clips`,
  CheckoutLabel: `Checkout`,
  Contact: `Contact`,
  Delete: `Delete`,
  Episodes: `Episodes`,
  FAQ: `FAQ`,
  FromThisEpisode: `From this episode`,
  FromThisPodcast: `From this podcast`,
  Login:  `Login`,
  Logout: `Log out`,
  MyClips: `My Clips`,
  MyPlaylists: `My Playlists`,
  MyPodcasts: `My Podcasts`,
  MyProfile: `My Profile`,
  Playlists: `Playlists`,
  PleaseVerifyEmail: `Please verify your email address to login.`,
  Podcasts: `Podcasts`,
  Premium: `Premium`,
  PremiumFreeTrial: `Premium (Free Trial)`,
  Profiles: `Profiles`,
  SendVerificationEmail: `send verification email`,
  Settings: `Settings`,
  Terms: `Terms`,
  TurnOnDark: `Turn on dark mode`,
  TurnOnLight: `Turn on light mode`
}
