export const core = {
  About: `About`,
  anonymous: `anonymous`,
  Cancel: `Cancel`,
  Clips: `Clips`,
  CheckoutLabel: `Checkout`,
  complete: `complete`,
  confirmed: `confirmed`,
  Contact: `Contact`,
  Delete: `Delete`,
  Episodes: `Episodes`,
  FAQ: `FAQ`,
  forgotPassword: `forgotPassword`,
  FromThisEpisode: `From this episode`,
  FromThisPodcast: `From this podcast`,
  Login:  `Login`,
  login: `login`,
  Logout: `Log out`,
  MyClips: `My Clips`,
  MyPlaylists: `My Playlists`,
  MyPodcasts: `My Podcasts`,
  MyProfile: `My Profile`,
  Playlists: `Playlists`,
  playlistOnPodverse: ` - playlist on Podverse `,
  PleaseVerifyEmail: `Please verify your email address to login.`,
  Podcasts: `Podcasts`,
  Premium: `Premium`,
  PremiumFreeTrial: `Premium (Free Trial)`,
  Profiles: `Profiles`,
  resetPassword: `resetPassword`,
  SendVerificationEmail: `send verification email`,
  sendVerificationEmail: `sendVerificationEmail`,
  Settings: `Settings`,
  Submit: `Submit`,
  Terms: `Terms`,
  TurnOnDark: `Turn on dark mode`,
  TurnOnLight: `Turn on light mode`,
  untitledPlaylist: `untitled playist`,
  untitledPodcast: `untitled podcast`,
  Update: `Update`
}
