/* eslint-disable @typescript-eslint/camelcase */

export const paths = {
  api: {
    add_or_remove: `/add-or-remove`,
    add_or_update_history_item: `/add-or-update-history-item`,
    auth: `/auth`,
    bitpay: `/bitpay`,
    category: `/category`,
    claim_account: `/claim-account`,
    download: `/download`,
    episode: `/episode`,
    get_authenticated_user_info: `/get-authenticated-user-info`,
    invoice: `/invoice`,
    login: `/login`,
    logout: `/logout`,
    mediaRef: `/mediaRef`,
    mediaRefs: `/mediaRefs`,
    order: `/order`,
    paypal: `/paypal`,
    playlist: `/playlist`,
    playlists: `/playlists`,
    podcast: `/podcast`,
    reset_password: `/reset-password`,
    send_reset_password: `/send-reset-password`,
    send_verification: `/send-verification`,
    sign_up: `/sign-up`,
    toggle_subscribe: `/toggle-subscribe`,
    update_history_item_playback_position: `/update-history-item-playback-position`,
    update_queue: `/update-queue`,
    user: `/user`,
    verify_email: `/verify-email`
  },
  web: {
    about: `/about`,
    clip: `/clip`,
    clips: `/clips`,
    episode: `/episode`,
    episodes: `/episodes`,
    faq: `/faq`,
    googlePlayStoreBadge: `https://play.google.com/intl/en_us/badges/static/images/badges/en_badge_web_generic.png`,
    home: `/`,
    license: `https://www.gnu.org/licenses/agpl-3.0.en.html`,
    membership: `/membership`,
    my_profile_clips: `/my-profile?type=clips`,
    my_profile: `/my-profile`,
    payment: `/payment`,
    paypal_confirming: `/paypal-confirming`,
    playlists: `/playlists`,
    podcast: `/podcast`,
    podcasts: `/podcasts`,
    profiles: `/profiles`,
    search: `/search`,
    settings_membership: `/settings#membership`,
    settings: `/settings`,
    support_podverse_fm: `mailto:support@podverse.fm`,
    terms: `/terms`,
    unspam: `http://www.unspam.com/noemailcollection/`
  }
}