export const query = {
  label:{
    All: `All`,
    AllPodcasts: `All Podcasts`,
    alphabetical: `alphabetical`,
    Categories: `Categories`,
    most_recent: `most recent`,
    random: `random`,
    Subscribed: `Subscribed`,
    top_all_time: `top - all time`,
    top_past_day: `top - past day`,
    top_past_month: `top - past month`,
    top_past_week: `top - past week`,
    top_past_year: `top - past year`
  },
  alphabetical: `alphabetical`,
  all_podcasts: `all-podcasts`,
  chronological: `chronological`,
  clips: `clips`,
  episodes: `episodes`,
  from_category: `from-category`,
  from_episode: `from-episode`,
  from_podcast: `from-podcast`,
  most_recent: `most-recent`,
  no_results: `no-results`,
  oldest: `oldest`,
  podcasts: `podcasts`,
  playlists: `playlists`,
  random: `random`,
  subscribed_only: `subscribed-only`,
  top_all_time: `top-all-time`,
  top_past_day: `top-past-day`,
  top_past_month: `top-past-month`,
  top_past_week: `top-past-week`,
  top_past_year: `top-past-year`
}