export { default as adminRouter } from './admin'
export { default as authRouter } from './auth'
export { default as devRouter } from './dev'
export { default as infoRouter } from './info'
export { default as mainRouter } from './main'
export { default as requestHandlerRouter } from './requestHandler'
