export const ROUTES = {
  ABOUT: '/about',
  ALBUMS: '/albums',
  ARTISTS: '/artists',
  CHANNELS: '/channels',
  CLIPS: '/clips',
  CONTACT: '/contact',
  DONATE: '/donate',
  EMBED: '/embed',
  EPISODES: '/episodes',
  HISTORY: '/history',
  MOBILE_APP: '/mobile-app',
  MY_CLIPS: '/my-clips',
  MY_PROFILE: '/my-profile',
  LIVESTREAMS: '/livestreams',
  PLAYLISTS: '/playlists',
  PODCAST: '/podcast',
  PODCASTS: '/podcasts',
  MEMBERSHIP: '/membership',
  PROFILES: '/profiles',
  QUEUE: '/queue',
  SEARCH: '/search',
  SETTINGS: '/settings',
  TERMS: '/terms',
  TRACKS: '/tracks',
  VIDEOS: '/videos'
};
