export const ROUTES = {
  ABOUT: '/about',
  ALBUMS: '/albums',
  CHANNELS: '/channels',
  CLIPS: '/clips',
  CONTACT: '/contact',
  DONATE: '/donate',
  EMBED: '/embed',
  EPISODES: '/episodes',
  HISTORY: '/history',
  MOBILE_APP: '/mobile-app',
  MUSIC: '/music',
  MY_CLIPS: '/my-clips',
  MY_PROFILE: '/my-profile',
  LIVESTREAMS: '/livestreams',
  PLAYLISTS: '/playlists',
  PODCASTS: '/podcasts',
  MEMBERSHIP: '/membership',
  PROFILES: '/profiles',
  QUEUE: '/queue',
  SEARCH: '/search',
  SETTINGS: '/settings',
  TERMS: '/terms',
  TRACKS: '/tracks',
  VIDEOS: '/videos',
  SOCIALS: {
    ACTIVITY_PUB: 'https://podcastindex.social/web/@podverse',
    DISCORD: 'https://discord.gg/6HkyNKR',
    GITHUB: 'https://github.com/podverse',
    MATRIX: 'https://matrix.to/#/#podverse-space:matrix.org',
    X: 'https://x.com/podverse'
  }
};
