export const pageKeys = {
  about: 'about',
  clip: 'clip_',
  clips: 'clips',
  episode: 'episode_',
  episodes: 'episodes',
  faq: 'faq',
  history: 'history',
  home: 'home',
  membership: 'membership',
  myProfile: 'my_profile',
  playlist: 'playlist_',
  playlists: 'playlists',
  podcast: 'podcast_',
  podcasts: 'podcasts',
  profile: 'profile_',
  profiles: 'profiles',
  queue: 'queue',
  redeem: 'redeem',
  search: 'search',
  settings: 'settings'
}
