import { GetServerSideProps } from 'next'
import Head from 'next/head'
import { useRouter } from 'next/router'
import { useTranslation } from 'next-i18next'
import { serverSideTranslations } from 'next-i18next/serverSideTranslations'
import OmniAural from "omniaural"
import type { Episode, Podcast } from 'podverse-shared'
import { useEffect, useState } from 'react'
import { List, PageHeader, PageScrollableContent, Pagination, PodcastListItem, PodcastPageHeader } from '~/components'
import { PV } from '~/resources'
import { getPodcastById, getPodcastsByQuery } from '~/services/podcast'
import { getAuthenticatedUserInfo } from '~/services/auth'
import { getEpisodesByQuery } from '~/services/episode'

type Props = {
  serverFilterFrom: string
  serverFilterPage: number
  serverFilterSort: string
  serverListData: Podcast[]
  serverListDataCount: number
  serverPodcast: Podcast
}

type FilterState = {
  filterFrom?: string
  filterPage?: number
  filterSort?: string
}

const keyPrefix = 'pages_podcast'

export default function Podcast(props: Props) {
  const { serverFilterFrom, serverFilterPage, serverFilterSort,
    serverListData, serverListDataCount, serverPodcast } = props

  const { t } = useTranslation()

  const [filterState, setFilterState] = useState({
    filterFrom: serverFilterFrom,
    filterSort: serverFilterSort,
    filterPage: serverFilterPage
  } as FilterState)
  const { filterFrom, filterPage, filterSort } = filterState
  const [listData, setListData] = useState<Episode[]>(serverListData)
  const [listDataCount, setListDataCount] = useState<number>(serverListDataCount)

  const pageCount = Math.ceil(listDataCount / PV.Config.QUERY_RESULTS_LIMIT_DEFAULT)

  const pageTitle = serverPodcast.title || t('untitledPodcast')

  useEffect(() => {
    (async () => {
      const { data } = await clientQueryPodcasts(
        { from: filterFrom, page: filterPage, sort: filterSort },
        filterState
      )
      const newListData = data[0]
      const newListCount = data[1]
      setListData(newListData)
      setListDataCount(newListCount)
    })()
  }, [filterFrom, filterSort, filterPage])

  return (
    <>
      <Head>
        <title>{pageTitle}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PodcastPageHeader podcast={serverPodcast} />
      {/* <PageScrollableContent>
        <List>
          {generatePodcastListElements(listData)}
        </List>
        <Pagination
          currentPageIndex={filterPage}
          handlePageNavigate={(newPage) => {
            setFilterState({ filterFrom, filterPage: newPage, filterSort })
          }}
          handlePageNext={() => {
            const newPage = filterPage + 1
            if (newPage <= pageCount) {
              setFilterState({ filterFrom, filterPage: newPage, filterSort })
            }
          }}
          handlePagePrevious={() => {
            const newPage = filterPage - 1
            if (newPage > 0) {
              setFilterState({ filterFrom, filterPage: newPage, filterSort })
            }
          }}
          pageCount={pageCount} />
      </PageScrollableContent> */}
    </>
  )
}

/* Server-side logic */

export const getServerSideProps: GetServerSideProps = async (ctx) => {
  const { locale, params, req } = ctx
  const { cookies } = req
  const { podcastId } = params

  let userInfo = null
  if (cookies.Authorization) {
    userInfo = await getAuthenticatedUserInfo(cookies.Authorization)
  }

  const serverFilterType = PV.Filters.type._episodes
  const serverFilterSort = PV.Filters.sort._mostRecent

  const serverFilterPage = 1

  const response = await getPodcastById(podcastId)
  const podcast = response.data

  let listData = []
  let listDataCount = 0
  if (serverFilterType === PV.Filters.type._episodes) {
    const response = await getEpisodesByQuery({
      podcastId: podcastId,
      sort: serverFilterSort
    })
    listData = response.data[0]
    listDataCount = response.data[1]
  } else {
    // handle mediaRefs query
  }

  return {
    props: {
      ...(await serverSideTranslations(locale, PV.i18n.fileNames.all)),
      // serverFilterFrom,
      // serverFilterPage,
      // serverFilterSort,
      // serverInitialUserInfo: userInfo,
      serverListData: listData,
      serverListDataCount: listDataCount,
      serverPodcast: podcast,
      serverSideCookies: cookies
    }
  }
}

/* Client-side logic */

type ClientQueryPodcasts = {
  from?: string
  page?: number
  sort?: string
}

const clientQueryPodcasts = async (
  { from, page, sort }: ClientQueryPodcasts,
  filterState: FilterState
) => {
  const finalQuery = {
    ...(from ? { from } : { from: filterState.filterFrom }),
    ...(page ? { page } : { page: filterState.filterPage }),
    ...(sort ? { sort } : { sort: filterState.filterSort })
  }
  return getPodcastsByQuery(finalQuery)
}

/* Helpers */

const generateFromOptions = (t: any) => [
  { label: t('All'), key: PV.Filters.from._all },
  { label: t('Subscribed'), key: PV.Filters.from._subscribed },
  { label: t('Categories'), key: PV.Filters.from._category }
]

const generateSortOptions = (t: any) => [
  // { label: t('Recent'), key: PV.Filters.sort._mostRecent },
  { label: t('Top - Past Day'), key: PV.Filters.sort._topPastDay },
  { label: t('Top - Past Week'), key: PV.Filters.sort._topPastWeek },
  { label: t('Top - Past Month'), key: PV.Filters.sort._topPastMonth },
  { label: t('Top - Past Year'), key: PV.Filters.sort._topPastYear },
  { label: t('Top - All Time'), key: PV.Filters.sort._topAllTime }
  // { label: t('Oldest'), key: PV.Filters.sort._oldest }
]

const generatePodcastListElements = (listItems: Podcast[]) => {
  return listItems.map((listItem, index) =>
    <PodcastListItem
      key={`${keyPrefix}-${index}`}
      podcast={listItem} />
  )
}
