export const actionTypes = {
  CURRENT_PAGE_LOAD_EPISODE: 'CURRENT_PAGE_LOAD_EPISODE',
  CURRENT_PAGE_LOAD_MEDIA_REF: 'CURRENT_PAGE_LOAD_MEDIA_REF',
  CURRENT_PAGE_LOAD_NOW_PLAYING_ITEM: 'CURRENT_PAGE_LOAD_NOW_PLAYING_ITEM',
  CURRENT_PAGE_LOAD_PODCAST: 'CURRENT_PAGE_LOAD_PODCAST',
  MEDIA_PLAYER_LOAD_EPISODE: 'MEDIA_PLAYER_LOAD_EPISODE',
  MEDIA_PLAYER_LOAD_MEDIA_REF: 'MEDIA_PLAYER_LOAD_MEDIA_REF',
  PLAYER_QUEUE_LOAD_PRIMARY_ITEMS: 'PLAYER_QUEUE_LOAD_PRIMARY_ITEMS',
  PLAYER_QUEUE_LOAD_SECONDARY_ITEMS: 'PLAYER_QUEUE_LOAD_SECONDARY_ITEMS'
}
