export const actionTypes = {
  CURRENT_PAGE_LOAD_EPISODE: 'CURRENT_PAGE_LOAD_EPISODE',
  CURRENT_PAGE_LOAD_LIST_ITEMS: 'CURRENT_PAGE_LOAD_LIST_ITEMS',
  CURRENT_PAGE_LOAD_MEDIA_REF: 'CURRENT_PAGE_LOAD_MEDIA_REF',
  CURRENT_PAGE_LOAD_NOW_PLAYING_ITEM: 'CURRENT_PAGE_LOAD_NOW_PLAYING_ITEM',
  CURRENT_PAGE_LOAD_PODCAST: 'CURRENT_PAGE_LOAD_PODCAST',
  MEDIA_PLAYER_SET_CLIP_FINISHED: 'MEDIA_PLAYER_SET_CLIP_FINISHED',
  MEDIA_PLAYER_LOAD_NOW_PLAYING_ITEM: 'MEDIA_PLAYER_LOAD_NOW_PLAYING_ITEM',
  MEDIA_PLAYER_UPDATE_PLAYING: 'MEDIA_PLAYER_UPDATE_PLAYING',
  PLAYER_QUEUE_LOAD_PRIMARY_ITEMS: 'PLAYER_QUEUE_LOAD_PRIMARY_ITEMS',
  PLAYER_QUEUE_LOAD_SECONDARY_ITEMS: 'PLAYER_QUEUE_LOAD_SECONDARY_ITEMS'
}
