import { GetServerSideProps } from 'next'
import Head from 'next/head'
import { useTranslation } from 'next-i18next'
import { serverSideTranslations } from 'next-i18next/serverSideTranslations'
import OmniAural, { useOmniAural } from 'omniaural'
import { useState } from 'react'
import {
  convertNowPlayingItemToEpisode, convertNowPlayingItemToMediaRef,
  NowPlayingItem
} from 'podverse-shared'
import {
  ClipListItem, EpisodeListItem, List, PageHeader, PageScrollableContent,
  Pagination,
  SideContent
} from '~/components'
import { Page } from '~/lib/utility/page'
import { PV } from '~/resources'
import { getServerSideAuthenticatedUserInfo } from '~/services/auth'
import { getServerSideUserQueueItems } from '~/services/userQueueItem'
import { getServerSideHistoryItems } from '~/services/userHistoryItem'

interface ServerProps extends Page {
  serverFilterPage: number
  serverUserHistoryItems: NowPlayingItem[]
  serverUserHistoryItemsCount: number
}

const keyPrefix = 'pages_history'

export default function History({ serverFilterPage, serverUserHistoryItems,
  serverUserHistoryItemsCount}: ServerProps) {
  /* Initialize */

  const { t } = useTranslation()
  const [filterPage, setFilterPage] = useState<number>(serverFilterPage)
  const [userHistoryItems, setUserHistoryItems] =
  useState<NowPlayingItem[]>(serverUserHistoryItems)
  const [userHistoryItemsCount, setUserHistoryItemsCount] =
  useState<number>(serverUserHistoryItemsCount)
  const [isEditing, setIsEditing] = useState<boolean>(false)
  const [userInfo] = useOmniAural('session.userInfo')
  const hasEditButton = !!userInfo
  
  const pageCount = Math.ceil(userHistoryItemsCount / PV.Config.QUERY_RESULTS_LIMIT_DEFAULT)

  const pageTitle = t('History')

  /* Function helpers */

  const _removeHistoryItemsAll = async () => {
    const answer = window.confirm(t('Are you sure you want to remove all your history items'))
    if (answer) {
      OmniAural.pageIsLoadingShow()
      await OmniAural.removeHistoryItemsAll()
      OmniAural.pageIsLoadingHide()
    }
  }

  /* Render Helpers */

  const generateHistoryListElements = (historyItems: NowPlayingItem[]) => {
    return historyItems.map((historyItem, index) => {
      if (historyItem.clipId) {
        const mediaRef = convertNowPlayingItemToMediaRef(historyItem)
        return (
          <ClipListItem
            episode={mediaRef.episode}
            handleRemove={() => OmniAural.removeHistoryItemMediaRef(mediaRef.id)}
            key={`${keyPrefix}-clip-${index}`}
            mediaRef={mediaRef}
            /* *TODO* Remove the "as any" below without throwing a Typescript error */
            podcast={mediaRef.episode.podcast as any}
            showImage
            showRemoveButton={isEditing} />
        )
      } else {
        const episode = convertNowPlayingItemToEpisode(historyItem)
        return (
          <EpisodeListItem
            episode={episode}
            handleRemove={() => OmniAural.removeHistoryItemEpisode(episode.id)}
            key={`${keyPrefix}-episode-${index}`}
            /* *TODO* Remove the "as any" below without throwing a Typescript error */
            podcast={episode.podcast as any}
            showImage
            showRemoveButton={isEditing} />
        )
      }
    })
  }

  return (
    <>
      <Head>
        <title>{pageTitle}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageHeader
        isEditing={isEditing}
        handleClearAllButton={_removeHistoryItemsAll}
        handleEditButton={() => setIsEditing(!isEditing)}
        hasEditButton={hasEditButton}
        text={t('History')} />
      <PageScrollableContent noMarginTop>
        <div className='row'>
          <div className='column flex-stretch'>
            <List>
              {generateHistoryListElements(userHistoryItems)}
            </List>
          </div>
          <div className='column'>
            <SideContent />
          </div>
        </div>
        <Pagination
          currentPageIndex={filterPage}
          handlePageNavigate={(newPage) => setFilterPage(newPage)}
          handlePageNext={() => {
            const newPage = filterPage + 1
            if (newPage <= pageCount) setFilterPage(newPage)
          }}
          handlePagePrevious={() => {
            const newPage = filterPage - 1
            if (newPage > 0) setFilterPage(newPage)
          }}
          pageCount={pageCount} />
      </PageScrollableContent>
    </>
  )
}

/* Server-Side Logic */

export const getServerSideProps: GetServerSideProps = async (ctx) => {
  const { req, locale } = ctx
  const { cookies } = req

  const userInfo = await getServerSideAuthenticatedUserInfo(cookies)
  const userQueueItems = await getServerSideUserQueueItems(cookies)
  const serverFilterPage = 1
  const historyItemsData = await getServerSideHistoryItems(serverFilterPage, cookies)
  const { userHistoryItems, userHistoryItemsCount } = historyItemsData

  const serverProps: ServerProps = {
    serverUserInfo: userInfo,
    serverUserQueueItems: userQueueItems,
    ...(await serverSideTranslations(locale, PV.i18n.fileNames.all)),
    serverCookies: cookies,
    serverFilterPage,
    serverUserHistoryItems: userHistoryItems,
    serverUserHistoryItemsCount: userHistoryItemsCount
  }

  return { props: serverProps }
}
