import Head from 'next/head'
// import Image from 'next/image'
import { useTranslation } from 'next-i18next'
import { serverSideTranslations } from 'next-i18next/serverSideTranslations'
import { PV } from '~/resources'

export default function Home() {
  const { t } = useTranslation(['common'])
  
  return (
    <div>
      <Head>
        <title>Podverse</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>{t('ContactSupport')}</h1>
    </div>
  )
}

export async function getStaticProps({ locale }) {
  return {
    props: {
      ...(await serverSideTranslations(locale, PV.i18n.fileNames.all))
    }
  }
}
