import { GetServerSideProps } from 'next'
import Head from 'next/head'
import { useTranslation } from 'next-i18next'
import { serverSideTranslations } from 'next-i18next/serverSideTranslations'
import OmniAural from 'omniaural'
import { Page } from '~/lib/utility/page'
import { PV } from '~/resources'
import { getServerSideAuthenticatedUserInfo } from '~/services/auth'
import { getServerSideUserQueueItems } from '~/services/userQueueItem'
import { MessageWithAction, PageHeader, PageScrollableContent } from '~/components'

interface ServerProps extends Page { }

const keyPrefix = 'pages_my_profile'

export default function MyProfile(props: ServerProps) {
  const { t } = useTranslation()

  return (
    <>
      <Head>
        <title>{t('My Profile')}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageHeader text={t('My Profile')} />
      <PageScrollableContent noMarginTop>
        <MessageWithAction
          actionLabel={t('Login')}
          actionOnClick={() => OmniAural.modalsLoginShow()}
          message={t('LoginToViewYourProfile')} />
      </PageScrollableContent>
    </>
  )
}

/* Server-Side Logic */

export const getServerSideProps: GetServerSideProps = async (ctx) => {
  const { req, locale } = ctx
  const { cookies } = req

  const userInfo = await getServerSideAuthenticatedUserInfo(cookies)

  if (userInfo) {
    return {
      redirect: {
        destination: `${PV.RoutePaths.web.profile}/${userInfo.id}`,
        permanent: false
      }
    }
  }

  const userQueueItems = await getServerSideUserQueueItems(cookies)

  const serverProps: ServerProps = {
    serverUserInfo: userInfo,
    serverUserQueueItems: userQueueItems,
    ...(await serverSideTranslations(locale, PV.i18n.fileNames.all)),
    serverCookies: cookies
  }

  return { props: serverProps }
}
