import { GetServerSideProps } from 'next'
import Head from 'next/head'
import { useRouter } from 'next/router'
import { useTranslation } from 'next-i18next'
import { serverSideTranslations } from 'next-i18next/serverSideTranslations'
import OmniAural, { useOmniAural } from 'omniaural'
import type { Playlist } from 'podverse-shared'
import { useEffect, useRef, useState } from 'react'
import {
  List, PageHeader, PageScrollableContent, Pagination, PlaylistListItem, PodcastListItem,
  scrollToTopOfPageScrollableContent
} from '~/components'
import { Page } from '~/lib/utility/page'
import { PV } from '~/resources'
import { getServerSideAuthenticatedUserInfo } from '~/services/auth'
import { getPodcastsByQuery } from '~/services/podcast'
import { getServerSideUserQueueItems } from '~/services/userQueueItem'
import { getServerSideLoggedInUserPlaylistsCombined } from '~/services/playlist'

interface ServerProps extends Page {
  serverPlaylistsCombined: {
    createdPlaylists: Playlist[]
    subscribedPlaylists: Playlist[]
  }
}

const keyPrefix = 'pages_playlists'

export default function Playlists({ serverPlaylistsCombined }: ServerProps) {

  /* Initialize */

  const { t } = useTranslation()
  const { createdPlaylists, subscribedPlaylists } = serverPlaylistsCombined
  const combinedPlaylists = createdPlaylists.concat(subscribedPlaylists)
  const pageTitle = t('Playlists')

  /* Render Helpers */

  const generatePlaylistElements = (listItems: Playlist[]) => {
    return listItems.map((listItem, index) =>
      <PlaylistListItem
        key={`${keyPrefix}-${index}`}
        playlist={listItem} />
    )
  }

  return (
    <>
      <Head>
        <title>{pageTitle}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageHeader text={t('Playlists')} />
      <PageScrollableContent>
        <List>
          {generatePlaylistElements(combinedPlaylists)}
        </List>
      </PageScrollableContent>
    </>
  )
}

/* Server-Side Logic */

export const getServerSideProps: GetServerSideProps = async (ctx) => {
  const { req, locale } = ctx
  const { cookies } = req

  const userInfo = await getServerSideAuthenticatedUserInfo(cookies)
  const userQueueItems = await getServerSideUserQueueItems(cookies)
  const combinedPlaylists = await getServerSideLoggedInUserPlaylistsCombined(cookies)

  const serverProps: ServerProps = {
    serverUserInfo: userInfo,
    serverUserQueueItems: userQueueItems,
    ...(await serverSideTranslations(locale, PV.i18n.fileNames.all)),
    serverCookies: cookies,
    serverPlaylistsCombined: combinedPlaylists
  }

  return { props: serverProps }
}
