import type { Podcast } from 'podverse-shared'
import { GetServerSideProps } from 'next'
import Head from 'next/head'
import { useRouter } from 'next/router'
import { useTranslation } from 'next-i18next'
import { serverSideTranslations } from 'next-i18next/serverSideTranslations'
import { useEffect, useState } from 'react'
import { List, PageHeader, PageScrollableContent, Pagination } from '~/components'
import { PV } from '~/resources'
import { getPodcastsByQuery } from '~/services/podcast'
import { PodcastListItem } from '~/components/PodcastListItem/PodcastListItem'

type Props = {
  serverListData: Podcast[]
  serverListDataCount: number
}

export default function Podcasts(props: Props) {
  const { serverListData, serverListDataCount } = props

  const router = useRouter()
  const { t } = useTranslation()
  const pageTitle = router.pathname == PV.RoutePaths.web.podcasts
    ? t('Podcasts')
    : t('Podverse')

  const sortOptions = generateSortOptions(t)
  const typeOptions = generateTypeOptions(t)

  const [listData, setListData] = useState<Podcast[]>(serverListData)
  const [listDataCount, setListDataCount] = useState<number>(serverListDataCount)

  const podcastListElements = generatePodcastListElements(listData)

  return (
    <>
      <Head>
        <title>{pageTitle}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PageHeader
        sortOptions={sortOptions}
        sortSelected={PV.Filters.sort._topPastYear}
        text={t('Podcasts')}
        typeOptions={typeOptions}
        typeSelected={PV.Filters.type._allPodcastsKey} />
      <PageScrollableContent>
        <List>
          {podcastListElements}
        </List>
        <Pagination
          currentPageIndex={1}
          onPageChange={() => { console.log('on page change') }}
          pageCount={10} />
      </PageScrollableContent>
    </>
  )
}

export const getServerSideProps: GetServerSideProps = async (ctx) => {
  const { req, locale } = ctx
  const { cookies } = req

  const podcasts = await getPodcastsByQuery({})
  const data = podcasts.data as Podcast[] || [[], 0]
  
  return {
    props: {
      ...(await serverSideTranslations(locale, PV.i18n.fileNames.all)),
      serverSideCookies: cookies,
      serverListData: data[0] || [],
      serverListDataCount: data[1] || 0
    }
  }
}

const generateTypeOptions = (t: any) => [
  { label: t('All'), key: PV.Filters.type._allPodcastsKey },
  { label: t('Subscribed'), key: PV.Filters.type._subscribedKey },
  { label: t('Categories'), key: PV.Filters.type._categoryKey }
]

const generateSortOptions = (t: any) => [
  { label: t('Recent'), key: PV.Filters.sort._mostRecentKey },
  { label: t('Top - Past Day'), key: PV.Filters.sort._topPastDay },
  { label: t('Top - Past Week'), key: PV.Filters.sort._topPastWeek },
  { label: t('Top - Past Month'), key: PV.Filters.sort._topPastMonth },
  { label: t('Top - Past Year'), key: PV.Filters.sort._topPastYear },
  { label: t('Top - All Time'), key: PV.Filters.sort._topAllTime },
  { label: t('Oldest'), key: PV.Filters.sort._oldestKey }
]

const keyPrefix = 'podcasts'
const generatePodcastListElements = (listItems: Podcast[]) => {
  return listItems.map((listItem, index) =>
    <PodcastListItem
      key={`${keyPrefix}-${index}`}
      podcast={listItem} />
  )
}
